# Generated by Django 3.0.5 on 2020-05-31 18:47

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('last_release', models.CharField(max_length=50, verbose_name='last release')),
                ('status', models.CharField(choices=[('new', 'new'), ('waiting', 'waiting'), ('done', 'done'), ('fail', 'fail')], db_index=True, default='new', max_length=50, verbose_name='status')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['name'],
            },
        ),
    ]
