# Generated by Django 3.0.9 on 2020-11-23 02:04

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('release', models.CharField(default='', max_length=50, verbose_name='release')),
                ('download_count', models.IntegerField(default=0, verbose_name='download count')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='favorite count')),
                ('retweet_count', models.IntegerField(default=0, verbose_name='retweet count')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['name'],
            },
        ),
    ]
