# Generated by Django 3.0.5 on 2020-05-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='downloads',
            field=models.IntegerField(default=0, verbose_name='downloads'),
        ),
    ]
