# Generated by Django 3.0.5 on 2020-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_project_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_release',
        ),
        migrations.AddField(
            model_name='project',
            name='release',
            field=models.CharField(default='', max_length=50, verbose_name='release'),
            preserve_default=False,
        ),
    ]
