# Generated by Django 3.0.5 on 2020-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20200531_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='release',
            field=models.CharField(default='', max_length=50, verbose_name='release'),
        ),
    ]
