# Generated by Django 3.0.4 on 2020-04-02 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('technology', models.CharField(choices=[('python', 'python'), ('node', 'node')], max_length=30, verbose_name='technology')),
                ('twitter_account', models.CharField(choices=[('pypackages', 'pypackages')], max_length=30, verbose_name='twitter account')),
                ('code_hosting', models.CharField(choices=[('github', 'github')], max_length=30, verbose_name='code hosting')),
                ('repository', models.CharField(max_length=200, verbose_name='repository')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'unique_together': {('name', 'technology'), ('code_hosting', 'repository')},
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('message', models.TextField(verbose_name='message')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('prerelease', models.BooleanField(verbose_name='prerelease')),
                ('published_at', models.DateTimeField(verbose_name='published at')),
                ('status', models.CharField(choices=[('new', 'new'), ('available', 'available'), ('tweeted', 'tweeted'), ('fail', 'fail')], db_index=True, default='new', max_length=30, verbose_name='status')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.Package')),
            ],
            options={
                'verbose_name': 'release',
                'verbose_name_plural': 'releases',
                'unique_together': {('name', 'package')},
            },
        ),
    ]
