# Generated by Django 3.0.5 on 2020-04-27 12:39

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('programming_language', models.CharField(choices=[('python', 'python')], max_length=50, verbose_name='programming language')),
                ('rank', models.PositiveIntegerField(db_index=True, default=0, verbose_name='rank')),
                ('repository', models.CharField(blank=True, max_length=200, verbose_name='repository')),
                ('keywords', models.CharField(max_length=255, verbose_name='keywords')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('homepage', models.CharField(max_length=255, verbose_name='homepage')),
                ('status', models.CharField(choices=[('new', 'new'), ('done', 'done'), ('fail', 'fail')], db_index=True, default='new', max_length=50, verbose_name='status')),
                ('message', models.TextField(blank=True, default='', verbose_name='message')),
                ('last_release', models.CharField(max_length=50, verbose_name='last release')),
                ('has_new_release', models.BooleanField(db_index=True, default=False, verbose_name='has new release')),
                ('stable_release_regex', models.CharField(blank=True, default='', max_length=30, verbose_name='stable release regex')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['name'],
                'unique_together': {('name', 'programming_language')},
            },
        ),
    ]
