# Generated by Django 3.0.4 on 2020-04-04 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('programming_language', models.CharField(choices=[('python', 'python'), ('javascript', 'javascript'), ('css', 'css')], max_length=50, verbose_name='programming language')),
                ('code_hosting', models.CharField(choices=[('github', 'github')], max_length=50, verbose_name='code hosting')),
                ('repository_owner', models.CharField(max_length=100, verbose_name='repository owner')),
                ('repository_name', models.CharField(max_length=100, verbose_name='repository name')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['name'],
                'unique_together': {('code_hosting', 'repository_owner', 'repository_name'), ('name', 'programming_language')},
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('message', models.TextField(verbose_name='message')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('status', models.CharField(choices=[('new', 'new'), ('available', 'available'), ('tweeted', 'tweeted'), ('fail', 'fail')], db_index=True, default='new', max_length=50, verbose_name='status')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watcher.Package')),
            ],
            options={
                'verbose_name': 'release',
                'verbose_name_plural': 'releases',
                'ordering': ['-created'],
                'unique_together': {('name', 'package')},
            },
        ),
    ]
