# Generated by Django 3.0.4 on 2020-04-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='object_id',
        ),
    ]
