# Generated by Django 3.0.4 on 2020-04-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_auto_20200405_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
