# Generated by Django 3.0.4 on 2020-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_auto_20200406_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='release_regex',
            field=models.CharField(default='((\\d+)(?:[\\.\\_]\\d+)+)$', max_length=100, verbose_name='release regex'),
            preserve_default=False,
        ),
    ]
