# Generated by Django 3.0.4 on 2020-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0005_package_release_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='hashtags',
            field=models.CharField(blank=True, max_length=255, verbose_name='hashtags'),
        ),
        migrations.AlterField(
            model_name='package',
            name='release_regex',
            field=models.CharField(help_text='v2.4.5 or 2.4.5 => ^v?((\\d+)(?:\\.\\d+)+)$ | v2.4.5rc1 or 2.4.5rc1 => ^v?((\\d+)(?:\\.\\d+)+\\w*)$', max_length=100, verbose_name='release regex'),
        ),
    ]
