# Generated by Django 3.0.4 on 2020-04-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0006_auto_20200409_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='package',
            name='home_page_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='home page url'),
        ),
        migrations.AlterField(
            model_name='package',
            name='release_regex',
            field=models.CharField(help_text='Ex. ^v?((\\d+)(?:\\.\\d+)+)$', max_length=100, verbose_name='release regex'),
        ),
    ]
