# Generated by Django 3.0.4 on 2020-04-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0007_auto_20200410_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='home_page_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='home page url'),
        ),
    ]
