# Generated by Django 3.0.4 on 2020-04-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0008_auto_20200410_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='home_page_url',
        ),
        migrations.AddField(
            model_name='package',
            name='site_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='site url'),
        ),
    ]
