# Generated by Django 3.0.4 on 2020-04-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0012_auto_20200412_1805'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('name', 'programming_language'), ('source_type', 'source_id')},
        ),
    ]
