# Generated by Django 3.0.4 on 2020-04-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0013_auto_20200412_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='package',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='tags'),
        ),
    ]
