# Generated by Django 3.0.4 on 2020-04-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0014_auto_20200413_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='code_hosting_repository',
            field=models.CharField(blank=True, help_text='repository owner/name', max_length=200, verbose_name='code hosting repository'),
        ),
        migrations.AddField(
            model_name='package',
            name='source',
            field=models.CharField(choices=[('github', 'github'), ('pypi', 'pypi')], default='pypi', max_length=50, verbose_name='source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='release_regex',
            field=models.CharField(blank=True, help_text='^v?((\\d+)(?:\\.\\d+)+)$', max_length=100, verbose_name='release regex'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('name', 'programming_language')},
        ),
        migrations.RemoveField(
            model_name='package',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='package',
            name='source_type',
        ),
    ]
