# Generated by Django 3.0.4 on 2020-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0015_auto_20200413_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='release_regex',
            field=models.CharField(help_text='^v?((\\d+)(?:\\.\\d+)+)$', max_length=100, verbose_name='release regex'),
        ),
    ]
