# Generated by Django 3.0.4 on 2020-04-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0017_auto_20200416_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='message',
            field=models.TextField(default='', verbose_name='message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('done', 'done'), ('fail', 'fail')], db_index=True, default='new', max_length=50, verbose_name='status'),
        ),
    ]
