# Generated by Django 3.0.5 on 2020-04-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0019_auto_20200416_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rank',
            field=models.PositiveIntegerField(default=999999999, verbose_name='rank'),
        ),
    ]
