# Generated by Django 3.0.5 on 2020-04-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0021_auto_20200416_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='release_regex',
            field=models.CharField(blank=True, max_length=100, verbose_name='release regex'),
        ),
    ]
