# Generated by Django 3.0.5 on 2020-04-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0022_package_release_regex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='release_regex',
        ),
        migrations.AddField(
            model_name='package',
            name='stable_regex',
            field=models.CharField(blank=True, max_length=100, verbose_name='stable regex'),
        ),
    ]
