# Generated by Django 3.0.5 on 2020-04-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0023_auto_20200418_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-status', '-created'], 'verbose_name': 'release', 'verbose_name_plural': 'releases'},
        ),
    ]
