# Generated by Django 3.0.4 on 2020-04-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0024_auto_20200418_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='has_new_release',
            field=models.BooleanField(default=False, verbose_name='has new release'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='last_release',
            field=models.CharField(default='', max_length=50, verbose_name='last release'),
            preserve_default=False,
        ),
    ]
