# Generated by Django 3.0.5 on 2020-04-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0025_auto_20200421_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Release',
        ),
    ]
