# Generated by Django 3.0.5 on 2020-04-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0026_delete_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='stable_regex',
        ),
    ]
