# Generated by Django 3.0.5 on 2020-04-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0027_remove_package_stable_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='has_new_release',
            field=models.BooleanField(db_index=True, default=False, verbose_name='has new release'),
        ),
    ]
