# Generated by Django 3.0.5 on 2020-04-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0030_package_stable_release_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='stable_release_regex',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='stable release regex'),
        ),
    ]
